type Student{
    name: String
    cod: Int
    course: Int
    id: Int
}

#consultas

type Query{

    allStudents: [Student]
    getStundentById(id: Int!): Student
    getStudentsByCourse(course: Int!): [Student]
    getStundentByCod(cod: Int!): Student
    numberOfStudents(): Int

}


type Mutation{

    createStudents(name: String, cod: Int, course: Int, id: Int): Student
    deleteStudentByID(id: Int!): Student
    
}